Adjust log processor to scrape correct log
18F/identity-idva-cf-metrics pull request #28
Opened 2021-12-02 21:59 UTC by shumatepf

The original cf-metrics was scraping for a crash log that is not available for rolling deployments, which makes up the majority of IDVA deployments. The log that is being used now does not contain meta information like the previous log so it is not possible to associate crashes with individual instances.
Example original log that was scraped:
```
OUT App instance exited with guid 64830a44-f116-1234-1234-9b3ca79dcc95 payload: {"instance"=>"e08ef3e1-3214-3214-4772-af66", "index"=>0, "cell_id"=>"cadc0ec5-8765-4e5f-4567-fa6a9a8e4fd7", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 134", "crash_count"=>2, "crash_timestamp"=>1638477297383879944, "version"=>"b1cbca53-4532-44a8-6778-018fb3a9f58f"}
```
Example new log that is scraped:
```
OUT Process has crashed with type: "web"
```
This log has been generating on all crashes but most likely wasn't used for the lack of meta information. For the purpose of seeing crash metrics, it is more valuable since the previously used log is only available for default deployments.

2021-12-02 22:59 UTC, dzaslavskiy commented
Is there a way to keep the logic for apps that do produce the correct logs and app the new logic as a fallback.

2021-12-02 23:06 UTC, dzaslavskiy reviewed
Is there a way to keep the logic for apps that do produce the correct logs and add the new logic as a fallback? Could we augment the data by querying the event api when a crash is found in the log?

2021-12-02 23:09 UTC, shumatepf commented
> Is there a way to keep the logic for apps that do produce the correct logs and add the new logic as a fallback?

I'm not sure since these this function is ran for all logs. It might be possible but seems like it would involve tampering with the way the main loop recognizes logs, which it doesn't at the moment. It just consumes a stream of logs.

2021-12-03 15:24 UTC, folksgl commented
Our goal with `cf-metrics` has always been to just "alert on the things". So if this implementation allows us to do that for crashes more reliably I'm all about it. To address @dzaslavskiy's concerns, I agree that it'd be _nice_ to preserve the existing functionality and fallback to this more generic one, but from a functional standpoint, we never used `cf-metrics` as a source of truth anyways. When we get a crash alert -- my first instinct is to look directly at the app logs, not the `cf-metrics` logs. So it doesn't concern me too terribly much that we may "lose" some detail here. Thoughts @dzaslavskiy ?

2021-12-03 15:29 UTC, folksgl requested changes

2021-12-03 15:29 UTC, folksgl commented on app/watcher.go
> +	if bytes.HasPrefix(logMessage.Message, []byte("Process has crashed with type:")) {
Less characters to compare means less processing spent comparing byte slices, while still conveying that what we're looking for are log messages that indicate a crash has occurred. 
```suggestion
	if bytes.HasPrefix(logMessage.Message, []byte("Process has crashed")) {
```

2021-12-06 17:01 UTC, shumatepf commented
> Could we augment the data by querying the event api when a crash is found in the log?

This is possible but would require reworking the cf-metrics engine. Moving forward that would be the ideal solution, since the events log contains much more useful information for crashes.

2021-12-06 17:05 UTC, shumatepf commented
For now, cf-metric only scrapes crashes based on the new changes with no preservation of existing functionality. Since the new change associates all crashes with the first instance, a mix between existing and new crash metric scrapes would result in an uninterpretable mess of instance crash metrics.

2021-12-06 17:24 UTC, folksgl approved these changes

2021-12-06 17:47 UTC, dzaslavskiy approved these changes

2021-12-06 17:47 UTC, merged